//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CardiacCT.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDI_ICON1                       127
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDS_EDIT_MENU                   306
#define IDI_ICON2                       312
#define IDI_ICON3                       313
#define IDD_DIALOG_DIRCONTENTS          314
#define IDD_DIALOG_3DPROCESS            316
#define IDI_ICON4                       320
#define IDD_DIALOG1                     321
#define IDD_DIALOG_PROGRESSBAR          321
#define IDD_DIALOG_WAIT                 323
#define IDD_DIALOG_3DPHANTOM            325
#define IDC_LIST1                       1000
#define IDC_LIST3                       1002
#define IDC_STATIC_2D                   1003
#define IDC_SCROLLBAR1                  1004
#define IDC_SCROLLBAR_2D                1004
#define IDC_SCROLLBAR_PHANTOM           1004
#define IDC_PROGRESS1                   1005
#define IDC_STATIC_3D                   1006
#define IDC_CHECK_Object                1007
#define IDC_CHECK3                      1009
#define IDC_CHECK_PLANE                 1009
#define IDC_EDIT_PIXEL_THRESHOLD        1010
#define IDC_EDIT_PIXEL_DOWN_THRESHOLD   1010
#define IDC_CHECK_COMPLETE              1011
#define IDC_CHECK_PIXEL_THRESHOLD       1012
#define IDC_EDIT_HU_THRESHOLD           1013
#define IDC_EDIT_HU_DOWN_THRESHOLD      1013
#define IDC_CHECK1                      1014
#define IDC_CHECK_HU_THRESHOLD          1014
#define IDC_CHECK_PHANTOM_3D_SEED       1014
#define IDC_EDIT_INTENSITY              1015
#define IDC_BUTTON_INTENSITY_PLUS       1016
#define IDC_BUTTON_INTENSITY_MINUS      1017
#define IDC_EDIT_DENSITY                1018
#define IDC_BUTTON_DENSITY_PLUS         1019
#define IDC_BUTTON_DENSITY_MINUS        1020
#define IDC_STATIC_INTENSITY            1021
#define IDC_STATIC_DENSITY              1022
#define IDC_STATIC_SLICES               1023
#define IDC_STATIC_PIXEL_THRESHOLD      1024
#define IDC_STATIC_PIXEL_DOWN_THRESHOLD 1024
#define IDC_STATIC_HU_THRESHOLD         1025
#define IDC_STATIC_HU_DOWN_THRESHOLD    1025
#define IDC_EDIT_SLICES                 1026
#define IDC_BUTTON_SLICES_PLUS          1027
#define IDC_BUTTON2                     1028
#define IDC_BUTTON_SLICES_MINUS         1028
#define IDC_BUTTON_PHANTOM_REGION_GROWING 1028
#define IDC_CHECK_3D_SEED               1029
#define IDC_EDIT_POS1                   1030
#define IDC_EDIT_POS2                   1031
#define IDC_EDIT_POS3                   1032
#define IDC_EDIT_POS4                   1033
#define IDC_BUTTON_3DSEED_CLEAR         1034
#define IDC_BUTTON_SEED_CHANGE          1035
#define IDC_STATIC_PIXEL_UP_THRESHOLD   1036
#define IDC_BUTTON_REGION_GROWING       1037
#define IDC_EDIT_POS5                   1038
#define IDC_EDIT_POS6                   1039
#define IDC_EDIT_POS7                   1040
#define IDC_EDIT4                       1041
#define IDC_EDIT_POS8                   1041
#define IDC_EDIT_PHANTOM_4              1041
#define IDC_BUTTON_PLANE_RESET          1042
#define IDC_BUTTON_2DSEED_CLEAR         1043
#define IDC_BUTTON_GROWING_CLEAR        1044
#define IDC_EDIT1                       1045
#define IDC_EDIT_RESULT                 1045
#define IDC_EDIT_PHANTOM_1              1045
#define IDC_BUTTON_DILATION             1046
#define IDC_BUTTON_GROWING_REMOVE       1047
#define IDC_BUTTON4                     1048
#define IDC_BUTTON_GROWING_RECOVERY     1048
#define IDC_CHECK_DISP_ORG              1049
#define IDC_CHECK4                      1050
#define IDC_CHECK_DISP_PRO0             1050
#define ID_EXIT                         1051
#define IDC_CHECK_SPINE                 1052
#define IDC_CHECK_STERNUM               1053
#define IDC_EDIT_S_KERNEL               1054
#define IDC_EDIT_N_KERNEL               1055
#define IDC_EDIT_PIX_TH                 1056
#define IDC_EDIT_SD_TH                  1057
#define IDC_EDIT_SD_CO                  1058
#define IDC_BUTTON_MID_FIX              1059
#define IDC_BUTTON_REUSE_LIMIT          1060
#define IDC_BUTTON_RECORD_LIMIT         1061
#define IDC_EDIT_PIXEL_UP_THRESHOLD     1062
#define IDC_STATIC_HU_UP_THRESHOLD      1063
#define IDC_EDIT_HU_UP_THRESHOLD        1064
#define IDC_CHECK_2D_SEED               1065
#define IDC_CHECK_2D_VERIFY             1066
#define IDC_CHECK_SPINE_VERIFY          1067
#define IDC_CHECK_STERNUM_VERIFY        1068
#define IDC_BUTTON_VERIFY_LINE_ERASE    1069
#define IDC_BUTTON_VERIFY_LINE_CLEAR    1070
#define IDC_BUTTON_VERIFY_LINE_REFERENCE 1071
#define IDC_BUTTON_VERIFY_LINE_CANCEL_REFERENCE 1072
#define IDC_BUTTON_VERIFY_CALCULATE     1073
#define IDC_EDIT_RESULT_2               1074
#define IDC_BUTTON_VERIFY_RECORD        1075
#define IDC_BUTTON_VERIFY_REUSE         1076
#define IDC_BUTTON_VERIFY_SAVE          1077
#define IDC_BUTTON_VERIFY_LOAD          1078
#define IDC_STATIC_PHANTOM_2D           1079
#define IDC_BUTTON_PHANTOM_OPEN         1080
#define IDC_STATIC_PHANTOM_3D           1081
#define IDC_EDIT_PHANTOM_2              1082
#define IDC_EDIT_PHANTOM_3              1083
#define IDC_EDIT_PHANTOM_5              1084
#define IDC_BUTTON_PHANTOM_SEED_CLEAR   1085
#define IDC_BUTTON_SALT_PEPPER_NOISE    1086
#define IDC_EDIT_NOISE_RATIO            1087
#define IDC_BUTTON_PHANTOM_GROWING_CLEAR 1088
#define IDC_BUTTON3                     1089
#define IDC_BUTTON_NOISE_CLEAR          1089
#define ID_Menu                         32771
#define ID_OPENDICOMDIR                 32772
#define ID_TOOLBTN_OPENDICOMDIR         32773
#define ID_TOOLBTN_DIRCONTENTS          32774
#define ID_TOOLBTN_3DPROCESS            32775
#define ID_TOOLBTN_PHANTOM              32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        327
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1090
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
